/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: RouterPath
 * Author: Victor
 * Date: 2024/05/11 18:16
 * Description: 
 * -----------------------------------------------------------------
 */

export class RouterPath {

 static readonly HOME_HOME_PAGE = 'module_home/HomePage';
 static readonly HOME_MAIN_PAGE = 'module_home/MainPage';
 static readonly ME_MAIN_PAGE = 'module_me/MainPage';

}