/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: Nucleus
 * Author: Victor
 * Date: 2024/05/13 11:58
 * Description: 
 * -----------------------------------------------------------------
 */
import { Comparable } from './Comparable';

export class Nucleus implements Comparable<Nucleus> {
  compareTo(other: Nucleus): number {
    return 0
  }
}