/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: OptWaves
 * Author: Victor
 * Date: 2024/05/13 12:26
 * Description: 
 * -----------------------------------------------------------------
 */
import { Waves } from './Waves'

export class OptWaves extends  Waves {
}