/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: OptWave
 * Author: Victor
 * Date: 2024/05/13 12:25
 * Description: 
 * -----------------------------------------------------------------
 */
import { Wave } from './Wave';

export class OptWave extends Wave {
}