/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: Waves
 * Author: Victor
 * Date: 2024/05/13 12:26
 * Description: 
 * -----------------------------------------------------------------
 */
import { OptWave } from './OptWave';

export class Waves extends OptWave {
}