/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: Wave
 * Author: Victor
 * Date: 2024/05/13 12:17
 * Description: 
 * -----------------------------------------------------------------
 */
import { HashMap, List } from '@kit.ArkTS';

export class Wave extends HashMap<String, List<String>> {

}